### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by tzaddi64** [ModernGamingWorld/Modern-s-Lite-Adventure#1]
**Modpack version**  2.0

**Describe the bug**
A clear and concise description of what the bug is.  I can't light the nether prefab portal

**Logs**
Input pastebin link to crash-report or `latest.log`, if applicable.
![2021-05-13_18 24 28](https://user-images.githubusercontent.com/42717053/118195241-d58e0000-b418-11eb-9aee-04bc38850741.png)

**Screenshots**

**Comment by ModernGamingWorld** [comment]
Not a bug, 

This mod aims to reinvent the vanilla Nether portal system. Instead of creating a dumb ol' obsidian rectangle and lighting it on fire, Nether portals now come in the form of Dimensional Rifts, which you'll find scattered deep underground. You'll have to find one of these Rifts in order to get to the Nether - but be careful, because it's now a one-way trip!

To get back from the Nether, you'll have to search for a Monolith. These are new, semi-rare structures that can be easily spotted from far away thanks to the beams they shoot into the sky. The block at the center of each Monolith that shoots this beam is called a Reclaimer, and it's the key to returning to the Overworld. However, the Reclaimer won't do much without a little power. In order to power it, you'll have to place a gold block on each of its four sides - something that shouldn't be too difficult to pull off in the Nether. Once powered, the Reclaimer has the ability to lift you back into the Overworld.

This mod is my own personal solution for meeting two design goals:

Make the Nether portal system more engaging and immersive. Should reward exploration rather than rely on an arbitrary obsidian rectangle.
Simulate dimension stacking. By having Dimensional Rifts spawn at the bottom of the world (and teleport players close to the top of the Nether), this mod simulates dimension stacking in an intuitive, vanilla-friendly way. Time to bring your Hellevators to Minecraft :)
If the new system this mod introduces sounds like too much of a pain for you - don't worry. You can bucket the Dimensional Plasma from a Dimensional Rift to bring it closer to your base, and you can mine the Reclaimer from a Monolith and place it right by where your Plasma teleports you to in the Nether. So, it's pretty close to a two-way portal, the only real difference being you'll have to find a Dimensional Rift and a Monolith first.

In addition, there's some bonus utility introduced by these new blocks just waiting to be explored. For example, the Reclaimers will levitate all entities that enter its beam, including players, mobs, and items. Can anyone say, potential for vanilla-friendly automation? How about, vanilla-style elevator?

Configurability

The mod features an extensive configuration. You can create and edit Dimensional Rift and Monolith variants for any dimension. You can fully control every aspect of eac
